name: Run tests and solutions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2019/02
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  solutions:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./2019/02
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Solution results
        run: npm run start
